### PR TITLE
Architectury 1.19.x Sinicized for the mod

### PR DESCRIPTION
**Pull request by yiobai**
{
  "text.autoconfig.chat_heads.title": "聊天头像",
  "text.autoconfig.chat_heads.option.offsetNonPlayerText": "偏移非玩家聊天文本",
  "text.autoconfig.chat_heads.option.offsetNonPlayerText.@Tooltip": "如果启用,所有文本将对齐",
  "text.autoconfig.chat_heads.option.explanation": "\"UUIDs\"? \"触发\"?",
  "text.autoconfig.chat_heads.option.explanation.@Tooltip[0]": "通常情况下,服务器会告诉我们是谁发的消息,",
  "text.autoconfig.chat_heads.option.explanation.@Tooltip[1]": "即发送者的UUID.然而,许多服务器没有.",
  "text.autoconfig.chat_heads.option.explanation.@Tooltip[2]": "他们甚至可以发送假的uuid.在这种情况下,我们需要使用.",
  "text.autoconfig.chat_heads.option.explanation.@Tooltip[3]": "触发,即我们根据消息内容进行猜测.",
  "text.autoconfig.chat_heads.option.explanation.@Tooltip[4]": "这种触发方法并不完美,因此可能会导致头部不匹配.",
  "text.autoconfig.chat_heads.option.senderDetection": "发件人检测",
  "text.autoconfig.chat_heads.option.senderDetection.@Tooltip[0]": "对于大多数服务器 \"UUID和触发式\" 工作正常.",
  "text.autoconfig.chat_heads.option.senderDetection.@Tooltip[1]": "如果服务器发送假UUID, \"仅触发式\"",
  "text.autoconfig.chat_heads.option.senderDetection.@Tooltip[2]": "必须使用.",
  "text.autoconfig.chat_heads.option.senderDetection.UUID_ONLY": "只有UUID",
  "text.autoconfig.chat_heads.option.senderDetection.UUID_AND_HEURISTIC": "UUID和触发式",
  "text.autoconfig.chat_heads.option.senderDetection.HEURISTIC_ONLY": "只有触发式",
  "text.autoconfig.chat_heads.option.smartHeuristics": "智能触发式",
  "text.autoconfig.chat_heads.option.smartHeuristics.@Tooltip[0]": "如果已知服务器发送uuid,则关闭触发式.",
  "text.autoconfig.chat_heads.option.smartHeuristics.@Tooltip[1]": "(适用于 \"UUID和触发式\" 发送方检测)",
  "text.chat_heads.config.error.title": "无法打开配置菜单",
  "text.chat_heads.config.error.no_cloth_config": "Cloth配置未安装!",
  "text.chat_heads.config.error.cloth_config_link": "在CurseForge打开Cloth配置页面"
}

### CODE REVIEW

**Comment by Fourmisain** [comment]
Thank you for the translations!
The pull request is not made right, but that is not a problem.
I will manually add in your translations.

I assume these are Simplified Chinese, aka `zh_cn`, right?

**Comment by yiobai** [comment]
> 感谢您的翻译！拉取请求不正确，但这不是问题。我将手动添加您的翻译。
> 
> 我想这些是简体中文，又名，对吧？`zh_cn`

yes

**Comment by Fourmisain** [comment]
There we go, I added it in https://github.com/dzwdz/chat_heads/commit/7ab405de4cd77cb5af83f38ab2c996415244560c.
I changed "Cloth配置" to "Cloth Config", since that is the name of the mod. ("Cloth" is the name of a different mod).

New version 0.8.1 is out on [Modrinth](https://modrinth.com/mod/chat-heads/versions) and soon on CurseForge too!

**Comment by yiobai** [comment]
> 

Ok, thank you

**Pull request closed without merging**
