### PR TITLE
Update zh_cn.json

### PR DESCRIPTION
**Pull request by qznfbnj**
Repeat the tooltip title once in the tooltip to use with the legendary tooltip (centered_title = true) that the user may have installed

### CODE REVIEW

**Comment by Fourmisain** [comment]
The translation is looking good, thank you very much!
(DeepL) 译文看起来不错，非常感谢!

It took me a while to understand what you mean with Legendary Tooltips.
It centers the "title" of the tooltip (the first line), which is supposed to be the item name.
However, it looks like Legendary Tooltips changes other tooltips as well:
我花了点时间才明白你说的Legendary Tooltips是什么意思。
它把工具提示的 "标题"（第一行）放在中心位置，这应该是物品名称。
然而，看起来Legendary Tooltips也会改变其他工具提示：

legendarytooltips

I understand why you duplicated the title, but I don't think we should be doing this.
This is a bug in Legendary Tooltips. We should report it if it hasn't been reported already.
我理解你为什么重复标题，但我认为我们不应该这样做。
这是Legendary Tooltips的一个错误。。如果还没有报告的话，我们也许应该报告它。

**Comment by qznfbnj** [comment]
Well, I'll report this issue to Legendary Tooltips.
By the way I just found out that the vanilla tooltip has a slightly bigger gap between the first and second row, is there a mod that removes this gap?

**Comment by Fourmisain** [comment]
I just reported the issue to Legendary Tooltips.

> By the way I just found out that the vanilla tooltip has a slightly bigger gap between the first and second row, is there a mod that removes this gap?

I also just noticed that vanilla does this. I am not aware of any mod that removes that gap.
The vanilla tooltips were probably designed for items and thus look bad in the menu.

**Comment by Fourmisain** [comment]
Phew, new releases for 1.20, 1.19.4, 1.19.2, Forge and Fabric on CurseForge and Modrinth are up!

**Pull request merged**
